language: minimal

env:
  - SERVER_USER=ec2-user SERVER_DNS=ec2-35-180-69-65.eu-west-3.compute.amazonaws.com

before_install:
  - openssl aes-256-cbc -K $encrypted_2c430460807a_key -iv $encrypted_2c430460807a_iv -in travis.pem.enc -out travis.pem -d
  - cat travis.pem

script:
  - docker build . -t bot:latest
  # Build container with database
  - docker build ./postgresql -t bot-db:latest
  # Save images to tar
  - docker save -o ./bot.tar bot:latest
  - docker save -o ./bot-db.tar bot-db:latest
  # Send tar ro EC2 instaces
  - scp -o StrictHostKeyChecking=no -i "travis.pem" ./bot.tar $SERVER_USER@$SERVER_DNS:~/bot.tar
  - scp -o StrictHostKeyChecking=no -i "travis.pem" ./bot-db.tar $SERVER_USER@$SERVER_DNS:~/bot-db.tar
  # run script with deploy code
 