language: minimal

script:
  - echo "$RSA_KEY" > travis.pem
  - make startup
  - docker save -o ./bot.tar bot:latest
  - docker save -o ./bot-db.tar bot-db:latest
  - scp ./bot.tar ec2-user@ec2-35-180-69-65.eu-west-3.compute.amazonaws.com/
  - scp ./bot-db.tar ec2-user@ec2-35-180-69-65.eu-west-3.compute.amazonaws.com/
  # run script with deploy code
