language: minimal

env:
  - SERVER_USER=ec2-user SERVER_DNS=ec2-35-180-69-65.eu-west-3.compute.amazonaws.com

script:
  - echo "$RSA_KEY" > travis.pem
  - chmod 400 travis.pem
  # Build images with bot
  - docker build . -t bot:latest
  # Build container with database
  - docker build ./postgresql -t bot-db:latest
  # Save images to tar
  - docker save -o ./bot.tar bot:latest
  - docker save -o ./bot-db.tar bot-db:latest
  # Send tar ro EC2 instaces
  - scp -o StrictHostKeyChecking=no -o PubkeyAuthentication="" -i "travis.pem" ./bot.tar $SERVER_USER@$SERVER_DNS:~/bot.tar
  - scp -o StrictHostKeyChecking=no -o PubkeyAuthentication="" -i "travis.pem" ./bot-db.tar $SERVER_USER@$SERVER_DNS:~/bot-db.tar
  # run script with deploy code
 